# Generated by Django 5.2.10 on 2026-01-11 19:00

from django.db import migrations, connection


def add_index_if_not_exists(apps, schema_editor):
    """Add index only if it doesn't exist."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'chunk_embed_embeddi_88d9e0_idx'
        """)
        
        if not cursor.fetchone():
            cursor.execute("""
                CREATE INDEX chunk_embed_embeddi_88d9e0_idx 
                ON chunk_embeddings (embedding_model)
            """)


def remove_index_if_exists(apps, schema_editor):
    """Remove index if it exists."""
    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS chunk_embed_embeddi_88d9e0_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_documents_and_chunks'),
    ]

    operations = [
        migrations.RunPython(add_index_if_not_exists, remove_index_if_exists),
    ]
