# Generated by Django 5.2.10 on 2026-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_chunkembedding_chunk_embed_embeddi_88d9e0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('EXTRACTED', 'Extracted'), ('INDEXING', 'Indexing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=20),
        ),
        # Tell Django's state about the index without creating it (already exists from migration 0005)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='chunkembedding',
                    index=models.Index(fields=['embedding_model'], name='chunk_embed_embeddi_88d9e0_idx'),
                ),
            ],
            database_operations=[],  # Index already exists in database
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'role', '-created_at'], name='messages_session_22e48e_idx'),
        ),
    ]
