# Generated by Django 5.2.10 on 2026-01-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_usage_count',
            field=models.BigIntegerField(default=0, help_text='Cumulative total token usage. This value is incremented when tokens are used and NEVER decreases, even when chats are deleted. This is the source of truth for all-time token usage.'),
        ),
    ]
