# Generated by ChatGPT on 2026-01-20
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_token_usage_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_openai_api_key",
            field=models.TextField(
                blank=True,
                default="",
                db_column="openai_api_key_encrypted",
                help_text="Encrypted OpenAI API key",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="_langfuse_public_key",
            field=models.TextField(
                blank=True,
                default="",
                db_column="langfuse_public_key_encrypted",
                help_text="Encrypted Langfuse public key",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="_langfuse_secret_key",
            field=models.TextField(
                blank=True,
                default="",
                db_column="langfuse_secret_key_encrypted",
                help_text="Encrypted Langfuse secret key",
            ),
        ),
    ]
