# Generated by OpenCode on 2026-01-21
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_add_encrypted_api_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_keys_validated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the current API key bundle was validated successfully",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="api_keys_validated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last successful API key validation",
                null=True,
            ),
        ),
    ]
